config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  get 'planes/index'
  get 'history', to: 'history#index'
  post 'takeoff', to: 'takeoff#create'


  root 'planes#index'

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plane.rb
class Plane < ApplicationRecord
  has_paper_trail

  enum status: %i(in_hangar waiting fly)

  scope :in_hangar, ->{ where(status: :in_hangar) }
  scope :waiting, ->{ where(status: :waiting) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/history_controller.rb
class HistoryController < ApplicationController
  def index
    @change_history = PaperTrail::Version.includes(:item).all
  end
end

app/controllers/planes_controller.rb
class PlanesController < ApplicationController
  def index
    @planes_in_hangar = Plane.in_hangar
    @waiting_planes   = Plane.waiting
  end
end

app/controllers/takeoff_controller.rb
class TakeoffController < ApplicationController

  def create
    @plane = Plane.find(params[:plane_id])
    @plane.update(status: :waiting)
    ActionCable.server.broadcast 'takeoff_channel', id: 1

    TakeoffWorker.perform_in(@plane.take_off_time.second, @plane.id)

    respond_to do |format|
      format.js { render layout: false }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/time_helper.rb
module TimeHelper
  def simple_datetime(date)
    date.strftime('%d.%m.%Y %H:%M')
  end
end

app/views/application/_navbar.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      = link_to 'Runway', :root, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          = link_to 'History', :history

app/views/history/index.haml
%table.table
  %thead
    %th Name
    %th Status
    %th Time update
  %tbody
    - @change_history.each do |plane|
      %tr
        %td= plane.reify.try(:name) || plane.item.try(:name)
        %td= plane.reify.try(:status) || plane.item.try(:status)
        %td= simple_datetime(plane.created_at)

app/views/layouts/application.haml
!!!
%html
  %head
    %title Runway
    = stylesheet_link_tag    'application', media: 'all'
    = boostrap_css_include_tag
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = action_cable_meta_tag
    = csrf_meta_tags
  %body
    = render 'navbar'
    .raw
      = yield

app/views/planes/_on_runway.haml
%tr{ data: { plane_id: plane.id } }
  %td= plane.name
  %td
    %span.label.label-warning= I18n.t("plane.status.#{plane.status}")
  %td= simple_datetime(plane.updated_at)

app/views/planes/_plane.haml
.panel.panel-default.plane-box.col-md-3.col-md-offset-1{ data: { plane_id: plane.id } }
  .panel-body
    %h5= plane.name
    %span.label.label-info= I18n.t("plane.status.#{plane.status}")
    %br
    %br
    = link_to 'On takeoff', takeoff_path(plane_id: plane.id), method: :post, class: 'btn btn-default', remote: true

app/views/planes/index.haml
.col-md-8#planes_in_hangar-box
  %h2 In hangar
  = render partial: 'plane', collection: @planes_in_hangar
.col-md-4
  %h2 On runway
  %table.table
    %thead
      %th Name
      %th Status
      %th Time
    %tbody#on_runway_table-box
      - @waiting_planes.each do |plane|
        = render 'on_runway', plane: plane

app/views/takeoff/create.js.erb
$("#planes_in_hangar-box").find(".panel[data-plane-id='<%= @plane.id %>']").remove();
$("#on_runway_table-box").append("<%= escape_javascript(render partial: 'planes/on_runway', locals: { plane: @plane } ) %>");